package main

import "time"

func mockCard() []Card {
	return []Card{
		{
			cardId:                          1,
			cardName:                        "HSBC Revolution",
			shortCardName:                   "HRV",
			cardType:                        0,
			cardImage:                       "",
			cardIssuer:                      "HSBC",
			localBaseReward:                 1,
			localBaseMiles:                  0.4,
			localBaseWhitelistCategories:    nil,
			localBaseBlacklistCategories:    nil,
			localBaseWhitelistPaymentTypes:  nil,
			localBaseBlacklistPaymentTypes:  nil,
			localBonusReward:                9,
			localBonusMiles:                 3.6,
			localBonusWhitelistCategories:   []int64{CATEGORY_ONLINE, CATEGORY_SHOPPING, CATEGORY_DINING},
			localBonusBlacklistCategories:   []int64{CATEGORY_DONATIONS, CATEGORY_EDUCATION, CATEGORY_INSURANCE, CATEGORY_UTILITIES},
			localBonusWhitelistPaymentTypes: []int64{PAYMENT_TYPE_CONTACTLESS, PAYMENT_TYPE_ONLINE, PAYMENT_TYPE_STRIPE},
			localBonusBlacklistPaymentTypes: nil,
			fcyBaseReward:                   1,
			fcyBaseMiles:                    0.4,
			fcyBaseWhitelistCategories:      nil,
			fcyBaseBlacklistCategories:      nil,
			fcyBonusReward:                  0,
			fcyBonusMiles:                   0,
			fcyBonusWhitelistCategories:     nil,
			fcyBonusBlacklistCategories:     nil,
			fcyBonusPaymentTypes:            nil,
			rounding:                        ROUNDING_ROUND,
			amountBlock:                     1.0,
			rewardCurrency:                  "HSBC Reward Points",
			capType:                         CAP_TYPE_CALENDAR_MONTH,
			cap:                             1000,
		},
		{
			cardId:                          2,
			cardName:                        "UOB Preferred Platinum Visa",
			shortCardName:                   "UOB PPV",
			cardType:                        0,
			cardImage:                       "",
			cardIssuer:                      "UOB",
			localBaseReward:                 1,
			localBaseMiles:                  0.4,
			localBaseWhitelistCategories:    nil,
			localBaseBlacklistCategories:    nil,
			localBaseWhitelistPaymentTypes:  nil,
			localBaseBlacklistPaymentTypes:  nil,
			localBonusReward:                9,
			localBonusMiles:                 3.6,
			localBonusWhitelistCategories:   []int64{CATEGORY_ONLINE, CATEGORY_SHOPPING, CATEGORY_DINING},
			localBonusBlacklistCategories:   nil,
			localBonusWhitelistPaymentTypes: []int64{PAYMENT_TYPE_CONTACTLESS},
			localBonusBlacklistPaymentTypes: nil,
			fcyBaseReward:                   1,
			fcyBaseMiles:                    0.4,
			fcyBaseWhitelistCategories:      nil,
			fcyBaseBlacklistCategories:      nil,
			fcyBonusReward:                  0,
			fcyBonusMiles:                   0,
			fcyBonusWhitelistCategories:     nil,
			fcyBonusBlacklistCategories:     nil,
			fcyBonusPaymentTypes:            nil,
			rounding:                        ROUNDING_ROUND_DOWN,
			amountBlock:                     5.0,
			rewardCurrency:                  "UNI$",
			capType:                         CAP_TYPE_CALENDAR_MONTH,
			cap:                             1000,
		},
		{
			cardId:                          3,
			cardName:                        "Citi Rewards MasterCard",
			shortCardName:                   "CRMC",
			cardType:                        0,
			cardImage:                       "",
			cardIssuer:                      "Citibank",
			localBaseReward:                 1,
			localBaseMiles:                  0.4,
			localBaseWhitelistCategories:    nil,
			localBaseBlacklistCategories:    nil,
			localBaseWhitelistPaymentTypes:  nil,
			localBaseBlacklistPaymentTypes:  nil,
			localBonusReward:                9,
			localBonusMiles:                 3.6,
			localBonusWhitelistCategories:   []int64{CATEGORY_ONLINE, CATEGORY_SHOPPING, CATEGORY_DINING},
			localBonusBlacklistCategories:   nil,
			localBonusWhitelistPaymentTypes: []int64{PAYMENT_TYPE_CONTACTLESS, PAYMENT_TYPE_ONLINE},
			localBonusBlacklistPaymentTypes: nil,
			fcyBaseReward:                   1,
			fcyBaseMiles:                    0.4,
			fcyBaseWhitelistCategories:      nil,
			fcyBaseBlacklistCategories:      nil,
			fcyBonusReward:                  0,
			fcyBonusMiles:                   0,
			fcyBonusWhitelistCategories:     nil,
			fcyBonusBlacklistCategories:     nil,
			fcyBonusPaymentTypes:            nil,
			rounding:                        ROUNDING_ROUND_DOWN,
			amountBlock:                     5.0,
			rewardCurrency:                  "Citi Points",
			capType:                         CAP_TYPE_CALENDAR_MONTH,
			cap:                             1000,
		},
		{
			cardId:                          3,
			cardName:                        "Citi Premier Miles",
			shortCardName:                   "CPM",
			cardType:                        0,
			cardImage:                       "",
			cardIssuer:                      "Citibank",
			localBaseReward:                 1,
			localBaseMiles:                  0.4,
			localBaseWhitelistCategories:    nil,
			localBaseBlacklistCategories:    nil,
			localBaseWhitelistPaymentTypes:  nil,
			localBaseBlacklistPaymentTypes:  nil,
			localBonusReward:                9,
			localBonusMiles:                 3.6,
			localBonusWhitelistCategories:   []int64{CATEGORY_ONLINE, CATEGORY_SHOPPING, CATEGORY_DINING},
			localBonusBlacklistCategories:   nil,
			localBonusWhitelistPaymentTypes: []int64{PAYMENT_TYPE_CONTACTLESS, PAYMENT_TYPE_ONLINE},
			localBonusBlacklistPaymentTypes: nil,
			fcyBaseReward:                   1,
			fcyBaseMiles:                    0.4,
			fcyBaseWhitelistCategories:      nil,
			fcyBaseBlacklistCategories:      nil,
			fcyBonusReward:                  0,
			fcyBonusMiles:                   0,
			fcyBonusWhitelistCategories:     nil,
			fcyBonusBlacklistCategories:     nil,
			fcyBonusPaymentTypes:            nil,
			rounding:                        ROUNDING_ROUND_DOWN,
			amountBlock:                     1.0,
			rewardCurrency:                  "Citi Miles",
			capType:                         CAP_TYPE_NO_CAP,
			cap:                             0,
		},
	}
}

func mockTransaction() Transaction {
	return Transaction{
		description: "Mock Trx",
		category:    CATEGORY_ONLINE,
		paymentType: PAYMENT_TYPE_CONTACTLESS,
		amount:      2000,
		currency:    "SGD",
		time:        time.Now().Unix(),
		cardId:      1,
	}
}
